name: Deploy React to AWS
on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@main

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: react-docker
          environment_name: React-docker-env
          version_label: ${{ github.sha }}
          existing_bucket_name: elasticbeanstalk-us-east-2-992382519986
          region: us-east-2
          deployment_package: deploy.zip